export const datas = [
  {
    key: "1",
    firstName: "Ali",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "2",
    firstName: "Sattor",
    lastName: "Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "3",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  {
    key: "4",
    firstName: "John",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "5",
    firstName: "Bahrom",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "6",
    firstName: "O'ktam",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "7",
    firstName: "Sobir",
    lastName: "Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "8",
    firstName: "Laylo",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  {
    key: "9",
    firstName: "Sunnant",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "10",
    firstName: "Bahor",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "11",
    firstName: "Leyla",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "12",
    firstName: "Alsiddin",
    lastName: "Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "13",
    firstName: "Alisher",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  {
    key: "14",
    firstName: "Ilhom",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "15",
    firstName: "Gulmurod",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "16",
    firstName: "John",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "17",
    firstName: "Jim",
    lastName: "Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "18",
    firstName: "Joe",
    lastName: "Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  {
    key: "19",
    firstName: "John",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "20",
    firstName: "John",
    lastName: "Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
];
